# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfer.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(614, 369)
        self.gridLayout_6 = QtWidgets.QGridLayout(dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tables_groupBox = QtWidgets.QGroupBox(dialog)
        self.tables_groupBox.setObjectName("tables_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.tables_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tables_listWidget = QtWidgets.QListWidget(self.tables_groupBox)
        self.tables_listWidget.setAlternatingRowColors(True)
        self.tables_listWidget.setObjectName("tables_listWidget")
        self.gridLayout.addWidget(self.tables_listWidget, 1, 0, 1, 1)
        self.preview_pushButton = QtWidgets.QPushButton(self.tables_groupBox)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.gridLayout.addWidget(self.preview_pushButton, 2, 0, 1, 1)
        self.select_all_checkBox = QtWidgets.QCheckBox(self.tables_groupBox)
        self.select_all_checkBox.setObjectName("select_all_checkBox")
        self.gridLayout.addWidget(self.select_all_checkBox, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.tables_groupBox, 0, 0, 1, 1)
        self.settings_groupBox = QtWidgets.QGroupBox(dialog)
        self.settings_groupBox.setObjectName("settings_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.settings_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.vacuum_checkBox = QtWidgets.QCheckBox(self.settings_groupBox)
        self.vacuum_checkBox.setObjectName("vacuum_checkBox")
        self.gridLayout_4.addWidget(self.vacuum_checkBox, 6, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.integer_type_label = QtWidgets.QLabel(self.settings_groupBox)
        self.integer_type_label.setObjectName("integer_type_label")
        self.gridLayout_3.addWidget(self.integer_type_label, 0, 0, 1, 1)
        self.integer_type_comboBox = QtWidgets.QComboBox(self.settings_groupBox)
        self.integer_type_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.integer_type_comboBox.setEditable(False)
        self.integer_type_comboBox.setObjectName("integer_type_comboBox")
        self.integer_type_comboBox.addItem("")
        self.integer_type_comboBox.addItem("")
        self.integer_type_comboBox.addItem("")
        self.integer_type_comboBox.addItem("")
        self.integer_type_comboBox.addItem("")
        self.integer_type_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.integer_type_comboBox, 0, 1, 1, 1)
        self.string_type_comboBox = QtWidgets.QComboBox(self.settings_groupBox)
        self.string_type_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.string_type_comboBox.setEditable(False)
        self.string_type_comboBox.setObjectName("string_type_comboBox")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.string_type_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.string_type_comboBox, 1, 1, 1, 1)
        self.string_type_label = QtWidgets.QLabel(self.settings_groupBox)
        self.string_type_label.setObjectName("string_type_label")
        self.gridLayout_3.addWidget(self.string_type_label, 1, 0, 1, 1)
        self.chunk_label = QtWidgets.QLabel(self.settings_groupBox)
        self.chunk_label.setObjectName("chunk_label")
        self.gridLayout_3.addWidget(self.chunk_label, 2, 0, 1, 1)
        self.chunk_spinBox = QtWidgets.QSpinBox(self.settings_groupBox)
        self.chunk_spinBox.setMaximum(999999999)
        self.chunk_spinBox.setObjectName("chunk_spinBox")
        self.gridLayout_3.addWidget(self.chunk_spinBox, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.foreign_keys_checkBox = QtWidgets.QCheckBox(self.settings_groupBox)
        self.foreign_keys_checkBox.setObjectName("foreign_keys_checkBox")
        self.gridLayout_4.addWidget(self.foreign_keys_checkBox, 4, 0, 1, 1)
        self.full_text_checkBox = QtWidgets.QCheckBox(self.settings_groupBox)
        self.full_text_checkBox.setObjectName("full_text_checkBox")
        self.gridLayout_4.addWidget(self.full_text_checkBox, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 8, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.log_label = QtWidgets.QLabel(self.settings_groupBox)
        self.log_label.setObjectName("log_label")
        self.gridLayout_2.addWidget(self.log_label, 0, 0, 1, 1)
        self.log_lineEdit = QtWidgets.QLineEdit(self.settings_groupBox)
        self.log_lineEdit.setReadOnly(True)
        self.log_lineEdit.setObjectName("log_lineEdit")
        self.gridLayout_2.addWidget(self.log_lineEdit, 0, 1, 1, 1)
        self.log_toolButton = QtWidgets.QToolButton(self.settings_groupBox)
        self.log_toolButton.setObjectName("log_toolButton")
        self.gridLayout_2.addWidget(self.log_toolButton, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.rowid_checkBox = QtWidgets.QCheckBox(self.settings_groupBox)
        self.rowid_checkBox.setObjectName("rowid_checkBox")
        self.gridLayout_4.addWidget(self.rowid_checkBox, 5, 0, 1, 1)
        self.buffered_checkBox = QtWidgets.QCheckBox(self.settings_groupBox)
        self.buffered_checkBox.setObjectName("buffered_checkBox")
        self.gridLayout_4.addWidget(self.buffered_checkBox, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.settings_groupBox, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.close_pushButton = QtWidgets.QPushButton(dialog)
        self.close_pushButton.setObjectName("close_pushButton")
        self.gridLayout_5.addWidget(self.close_pushButton, 0, 3, 1, 1)
        self.about_pushButton = QtWidgets.QPushButton(dialog)
        self.about_pushButton.setObjectName("about_pushButton")
        self.gridLayout_5.addWidget(self.about_pushButton, 0, 2, 1, 1)
        self.transfer_pushButton = QtWidgets.QPushButton(dialog)
        self.transfer_pushButton.setObjectName("transfer_pushButton")
        self.gridLayout_5.addWidget(self.transfer_pushButton, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 2)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.select_all_checkBox, self.tables_listWidget)
        dialog.setTabOrder(self.tables_listWidget, self.preview_pushButton)
        dialog.setTabOrder(self.preview_pushButton, self.log_lineEdit)
        dialog.setTabOrder(self.log_lineEdit, self.log_toolButton)
        dialog.setTabOrder(self.log_toolButton, self.integer_type_comboBox)
        dialog.setTabOrder(self.integer_type_comboBox, self.string_type_comboBox)
        dialog.setTabOrder(self.string_type_comboBox, self.chunk_spinBox)
        dialog.setTabOrder(self.chunk_spinBox, self.full_text_checkBox)
        dialog.setTabOrder(self.full_text_checkBox, self.buffered_checkBox)
        dialog.setTabOrder(self.buffered_checkBox, self.foreign_keys_checkBox)
        dialog.setTabOrder(self.foreign_keys_checkBox, self.rowid_checkBox)
        dialog.setTabOrder(self.rowid_checkBox, self.vacuum_checkBox)
        dialog.setTabOrder(self.vacuum_checkBox, self.transfer_pushButton)
        dialog.setTabOrder(self.transfer_pushButton, self.about_pushButton)
        dialog.setTabOrder(self.about_pushButton, self.close_pushButton)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Berudele"))
        self.tables_groupBox.setTitle(_translate("dialog", "SQLite Tables:"))
        self.preview_pushButton.setText(_translate("dialog", "Preview"))
        self.select_all_checkBox.setText(_translate("dialog", "Select all"))
        self.settings_groupBox.setTitle(_translate("dialog", "Settings:"))
        self.vacuum_checkBox.setText(_translate("dialog", "Vacuum"))
        self.integer_type_label.setText(_translate("dialog", "MySQL default integer field type:"))
        self.integer_type_comboBox.setItemText(0, _translate("dialog", "Default"))
        self.integer_type_comboBox.setItemText(1, _translate("dialog", "TINYINT"))
        self.integer_type_comboBox.setItemText(2, _translate("dialog", "SMALLINT"))
        self.integer_type_comboBox.setItemText(3, _translate("dialog", "MEDIUMINT"))
        self.integer_type_comboBox.setItemText(4, _translate("dialog", "INT"))
        self.integer_type_comboBox.setItemText(5, _translate("dialog", "BIGINT"))
        self.string_type_comboBox.setItemText(0, _translate("dialog", "Default"))
        self.string_type_comboBox.setItemText(1, _translate("dialog", "CHAR"))
        self.string_type_comboBox.setItemText(2, _translate("dialog", "VARCHAR"))
        self.string_type_comboBox.setItemText(3, _translate("dialog", "BINARY"))
        self.string_type_comboBox.setItemText(4, _translate("dialog", "VARBINARY"))
        self.string_type_comboBox.setItemText(5, _translate("dialog", "TINYBLOB"))
        self.string_type_comboBox.setItemText(6, _translate("dialog", "TINYTEXT"))
        self.string_type_comboBox.setItemText(7, _translate("dialog", "TEXT"))
        self.string_type_comboBox.setItemText(8, _translate("dialog", "BLOB"))
        self.string_type_comboBox.setItemText(9, _translate("dialog", "MEDIUMTEXT"))
        self.string_type_comboBox.setItemText(10, _translate("dialog", "MEDIUMBLOB"))
        self.string_type_comboBox.setItemText(11, _translate("dialog", "LONGTEXT"))
        self.string_type_comboBox.setItemText(12, _translate("dialog", "LONGBLOB"))
        self.string_type_label.setText(_translate("dialog", "MySQL default string field type:"))
        self.chunk_label.setText(_translate("dialog", "Chunk reading/writing SQL records:"))
        self.foreign_keys_checkBox.setText(_translate("dialog", "Do not transfer foreign keys"))
        self.full_text_checkBox.setText(_translate("dialog", " Use FULLTEXT indexes on TEXT columns"))
        self.log_label.setText(_translate("dialog", "Log:"))
        self.log_toolButton.setText(_translate("dialog", "..."))
        self.rowid_checkBox.setText(_translate("dialog", "Transfer rowid columns"))
        self.buffered_checkBox.setText(_translate("dialog", "Use MySQLCursorBuffered for reading the MySQL database"))
        self.close_pushButton.setText(_translate("dialog", "Close"))
        self.about_pushButton.setText(_translate("dialog", "About..."))
        self.transfer_pushButton.setText(_translate("dialog", "Transfer"))


